WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=2, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025E85EC51D0>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=1, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025E86261890>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session
WARNING  urllib3.connectionpool:connectionpool.py:812 Retrying (Retry(total=0, connect=None, read=None, redirect=None, status=None)) after connection broken by 'NewConnectionError('<urllib3.connection.HTTPConnection object at 0x0000025E86262950>: Failed to establish a new connection: [WinError 10061] No connection could be made because the target machine actively refused it')': /session