{"uuid": "b08d4c50-91a3-4b0e-a7f2-d278ec8b00df", "children": ["0a7dc256-e988-44af-851d-09687f157b99", "1c3b31d4-9dcc-4011-bab5-209cdddf5c43", "6c3cfce9-6f7c-4e17-92fd-38df433ac681", "49f70fd2-4479-47bd-bca5-47c65f28c561", "068dd2d9-363a-4d39-a48e-c7ae14168877", "039f00a6-44e6-4b4c-be4b-db440c9363bb", "7ff61d4c-667d-42c7-8157-18cceee670ea", "09c145aa-50c6-44af-8c8d-f9983c8f73e8"], "befores": [{"name": "init_web_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=112.0.5615.138)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x0037DCE3+50899]\n\t(No symbol) [0x0030E111]\n\t(No symbol) [0x00215588]\n\t(No symbol) [0x00211D87]\n\t(No symbol) [0x00208B45]\n\t(No symbol) [0x00209B1A]\n\t(No symbol) [0x00208E20]\n\t(No symbol) [0x00208275]\n\t(No symbol) [0x0020820C]\n\t(No symbol) [0x00206F06]\n\t(No symbol) [0x00207668]\n\t(No symbol) [0x00216D22]\n\t(No symbol) [0x0026E631]\n\t(No symbol) [0x0025B8FC]\n\t(No symbol) [0x0026E01C]\n\t(No symbol) [0x0025B6F6]\n\t(No symbol) [0x00237708]\n\t(No symbol) [0x0023886D]\n\tGetHandleVerifier [0x005E3EAE+2566302]\n\tGetHandleVerifier [0x006192B1+2784417]\n\tGetHandleVerifier [0x0061327C+2759788]\n\tGetHandleVerifier [0x00415740+672048]\n\t(No symbol) [0x00318872]\n\t(No symbol) [0x003141C8]\n\t(No symbol) [0x003142AB]\n\t(No symbol) [0x003071B7]\n\tBaseThreadInitThunk [0x76727D69+25]\n\tRtlInitializeExceptionChain [0x775AB74B+107]\n\tRtlClearBits [0x775AB6CF+191]\n\n", "trace": "  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Automation\\Final_Proj_Aut_Py\\test_cases\\conftest.py\", line 47, in init_web_driver\n    driver.get(get_data('Url'))\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\selenium\\webdriver\\support\\event_firing_webdriver.py\", line 81, in get\n    self._dispatch(\"navigate_to\", (url, self._driver), \"get\", (url,))\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\selenium\\webdriver\\support\\event_firing_webdriver.py\", line 114, in _dispatch\n    result = getattr(self._driver, d_call)(*d_args)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 449, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1682172296714, "stop": 1682172304528}], "start": 1682172296714, "stop": 1682172306208}