{"uuid": "0bfdb04c-3738-4416-a689-08b8a39e1265", "children": ["764a2a68-1a62-46d0-8d58-fb4e830f0c53", "2d4eb8fe-bcab-4dfe-a957-38640b3f57d2", "aee6b311-0b46-4b8b-8634-94ec55da458f", "af3f4602-bc31-4c58-b0b6-0b6827331c93", "1b06dadb-369c-4b56-899a-b41edad80387", "b1e65283-ac20-47e9-a7a4-8a01274e9586", "87d221b2-3ee2-4583-b19d-e70a52d5a28c", "6f5789df-7779-4158-98cc-3867b819902d"], "befores": [{"name": "init_web_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=110.0.5481.178)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x006537D3]\n\t(No symbol) [0x005E8B81]\n\t(No symbol) [0x004EB36D]\n\t(No symbol) [0x004E772D]\n\t(No symbol) [0x004DDC65]\n\t(No symbol) [0x004DF033]\n\t(No symbol) [0x004DDF02]\n\t(No symbol) [0x004DD324]\n\t(No symbol) [0x004DD241]\n\t(No symbol) [0x004DBC95]\n\t(No symbol) [0x004DC518]\n\t(No symbol) [0x004ECF4C]\n\t(No symbol) [0x00551E01]\n\t(No symbol) [0x0053B41C]\n\t(No symbol) [0x00551215]\n\t(No symbol) [0x0053B216]\n\t(No symbol) [0x00510D97]\n\t(No symbol) [0x0051253D]\n\tGetHandleVerifier [0x008CABF2+2510930]\n\tGetHandleVerifier [0x008F8EC1+2700065]\n\tGetHandleVerifier [0x008FC86C+2714828]\n\tGetHandleVerifier [0x00703480+645344]\n\t(No symbol) [0x005F0FD2]\n\t(No symbol) [0x005F6C68]\n\t(No symbol) [0x005F6D4B]\n\t(No symbol) [0x00600D6B]\n\tBaseThreadInitThunk [0x76957D69+25]\n\tRtlInitializeExceptionChain [0x77ABBB9B+107]\n\tRtlClearBits [0x77ABBB1F+191]\n\n", "trace": "  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Automation\\Final_Proj_Aut_Py\\test_cases\\conftest.py\", line 49, in init_web_driver\n    driver.get(get_data('Url'))\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\selenium\\webdriver\\support\\event_firing_webdriver.py\", line 81, in get\n    self._dispatch(\"navigate_to\", (url, self._driver), \"get\", (url,))\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\selenium\\webdriver\\support\\event_firing_webdriver.py\", line 114, in _dispatch\n    result = getattr(self._driver, d_call)(*d_args)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 449, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1677613946302, "stop": 1677613955884}], "start": 1677613946302, "stop": 1677613958063}