{"uuid": "7e8630af-6117-4cf0-84cb-48f68a7cd35f", "children": ["04429162-780b-4856-bf20-bf792b88d110"], "befores": [{"name": "init_web_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=112.0.5615.138)\nStacktrace:\nBacktrace:\n\tGetHandleVerifier [0x0105DCE3+50899]\n\t(No symbol) [0x00FEE111]\n\t(No symbol) [0x00EF5588]\n\t(No symbol) [0x00EF1D87]\n\t(No symbol) [0x00EE8B45]\n\t(No symbol) [0x00EE9B1A]\n\t(No symbol) [0x00EE8E20]\n\t(No symbol) [0x00EE8275]\n\t(No symbol) [0x00EE820C]\n\t(No symbol) [0x00EE6F06]\n\t(No symbol) [0x00EE7668]\n\t(No symbol) [0x00EF6D22]\n\t(No symbol) [0x00F4E631]\n\t(No symbol) [0x00F3B8FC]\n\t(No symbol) [0x00F4E01C]\n\t(No symbol) [0x00F3B6F6]\n\t(No symbol) [0x00F17708]\n\t(No symbol) [0x00F1886D]\n\tGetHandleVerifier [0x012C3EAE+2566302]\n\tGetHandleVerifier [0x012F92B1+2784417]\n\tGetHandleVerifier [0x012F327C+2759788]\n\tGetHandleVerifier [0x010F5740+672048]\n\t(No symbol) [0x00FF8872]\n\t(No symbol) [0x00FF41C8]\n\t(No symbol) [0x00FF42AB]\n\t(No symbol) [0x00FE71B7]\n\tBaseThreadInitThunk [0x75677D69+25]\n\tRtlInitializeExceptionChain [0x777BB74B+107]\n\tRtlClearBits [0x777BB6CF+191]\n\n", "trace": "  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Automation\\Final_Proj_Aut_Py\\test_cases\\conftest.py\", line 47, in init_web_driver\n    driver.get(get_data('Url'))\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\selenium\\webdriver\\support\\event_firing_webdriver.py\", line 81, in get\n    self._dispatch(\"navigate_to\", (url, self._driver), \"get\", (url,))\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\selenium\\webdriver\\support\\event_firing_webdriver.py\", line 114, in _dispatch\n    result = getattr(self._driver, d_call)(*d_args)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 449, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 440, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Program Files\\Python311\\Lib\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 245, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1682189424598, "stop": 1682189431826}], "start": 1682189424598, "stop": 1682189432331}