{"uuid": "b7b230fb-2004-4207-8286-b7bef1271eaf", "children": ["1b0d1a06-b5c9-4fcb-bc3f-424c74fd5e09", "bae26459-7e1c-46a4-955c-ba16359994e5", "49dbe683-b9c9-46e1-ba82-a4b2eae0f400", "bcaf00aa-ec8d-4c51-9803-a251472d6e04", "113ecb06-ce9e-49d6-a142-d7bd4efa770b", "829b337b-3d8f-442d-99de-64f23e963edc", "b42d5545-fafa-42e8-a3e2-15549b639213"], "befores": [{"name": "init_web_driver", "status": "broken", "statusDetails": {"message": "selenium.common.exceptions.WebDriverException: Message: unknown error: net::ERR_CONNECTION_REFUSED\n  (Session info: chrome=109.0.5414.75)\nStacktrace:\nBacktrace:\n\t(No symbol) [0x00EA6643]\n\t(No symbol) [0x00E3BE21]\n\t(No symbol) [0x00D3DA9D]\n\t(No symbol) [0x00D39E22]\n\t(No symbol) [0x00D2FCFD]\n\t(No symbol) [0x00D31101]\n\t(No symbol) [0x00D2FFDD]\n\t(No symbol) [0x00D2F3BC]\n\t(No symbol) [0x00D2F2D8]\n\t(No symbol) [0x00D2DC68]\n\t(No symbol) [0x00D2E512]\n\t(No symbol) [0x00D3F75B]\n\t(No symbol) [0x00DA7727]\n\t(No symbol) [0x00D8FD7C]\n\t(No symbol) [0x00DA6B09]\n\t(No symbol) [0x00D8FB76]\n\t(No symbol) [0x00D649C1]\n\t(No symbol) [0x00D65E5D]\n\tGetHandleVerifier [0x0111A142+2497106]\n\tGetHandleVerifier [0x011485D3+2686691]\n\tGetHandleVerifier [0x0114BB9C+2700460]\n\tGetHandleVerifier [0x00F53B10+635936]\n\t(No symbol) [0x00E44A1F]\n\t(No symbol) [0x00E4A418]\n\t(No symbol) [0x00E4A505]\n\t(No symbol) [0x00E5508B]\n\tBaseThreadInitThunk [0x76187D69+25]\n\tRtlInitializeExceptionChain [0x7742BB9B+107]\n\tRtlClearBits [0x7742BB1F+191]\n\n", "trace": "  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\pluggy\\_callers.py\", line 39, in _multicall\n    res = hook_impl.function(*args)\n          ^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\_pytest\\fixtures.py\", line 1129, in pytest_fixture_setup\n    result = call_fixture_func(fixturefunc, request, kwargs)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\_pytest\\fixtures.py\", line 901, in call_fixture_func\n    fixture_result = next(generator)\n                     ^^^^^^^^^^^^^^^\n  File \"C:\\Automation\\Final_Proj_Aut_Py\\test_cases\\conftest.py\", line 31, in init_web_driver\n    driver.get(get_data('Url'))\n  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\support\\event_firing_webdriver.py\", line 82, in get\n    self._dispatch(\"navigate_to\", (url, self._driver), \"get\", (url,))\n  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\support\\event_firing_webdriver.py\", line 115, in _dispatch\n    result = getattr(self._driver, d_call)(*d_args)\n             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^\n  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 455, in get\n    self.execute(Command.GET, {\"url\": url})\n  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\webdriver.py\", line 444, in execute\n    self.error_handler.check_response(response)\n  File \"C:\\Users\\barka\\AppData\\Roaming\\Python\\Python311\\site-packages\\selenium\\webdriver\\remote\\errorhandler.py\", line 249, in check_response\n    raise exception_class(message, screen, stacktrace)\n"}, "start": 1674570899651, "stop": 1674570909774}], "start": 1674570899651, "stop": 1674570910639}